import Men1Icon from "@/assets/icons/solid/sexy_man_1.svg"
import Men2Icon from "@/assets/icons/solid/sexy_man_2.svg"
import Men3Icon from "@/assets/icons/solid/sexy_man_3.svg"
import FakeDocument from "@/assets/icons/solid/fake_document.svg"
import UserIcon from "@/assets/icons/solid/user.svg"
import DashboardIcon from "@/assets/icons/solid/dashboard.svg"
import HeartIcon from "@/assets/icons/solid/heart.svg"
import LogoutIcon from "@/assets/icons/solid/logout.svg"
import NotificationIcon from "@/assets/icons/solid/notification.svg"
import SettingIcon from "@/assets/icons/solid/setting.svg"
import UserSettingIcon from "@/assets/icons/solid/user-setting.svg"
import BulbIcon from "@/assets/icons/solid/bulb.svg"
import UserUploadDpIcon from "@/assets/icons/solid/user-uploaddp.svg"

export { Men1Icon, Men2Icon, Men3Icon, FakeDocument, UserIcon, DashboardIcon, HeartIcon, LogoutIcon, NotificationIcon, SettingIcon, UserSettingIcon, BulbIcon, UserUploadDpIcon }